### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by Julyski** [TheOnlyWayUp/WattpadDownloader#26]
Cannot paste the URL, it only shows story code but not the whole link.

**Comment by AaronBenDaniel** [comment]
Do you mean that, for example, if you paste `wattpad.com/story/237369078-wattpad-books-presents` into the `Story URL` box, only `237369078` appears?

**Comment by Julyski** [comment]
Ok, thanks.

**Comment by AaronBenDaniel** [comment]
If you have future trouble with WattpadDownloader, you can find support on our [Discord server](https://discord.gg/P9RHC4KCwd).

**Comment by Julyski** [comment]
Oh, can you please check on this?

**Comment by Julyski** [comment]
Oh, just saw on Discord that you're fixing the bug. I'll wait. Thank you.

**Comment by AaronBenDaniel** [comment]
> Oh, can you please check on this?

What do you mean by "this"? Do you mean #25?

**Comment by Julyski** [comment]
Lease see attached scrrenshot.

**Comment by AaronBenDaniel** [comment]
I don't see any images in any of your comments here.

**Comment by Julyski** [comment]
That's the same error I get, it only shows the story ID. This is the first
time I had this issue while downloading, I thought I am the ony one who has
this trouble.

**Comment by Julyski** [comment]
The same issue that is in Discord, the one that sowansow replied.

**Comment by Julyski** [comment]
***@***.***> New bug just dropped. When I paste this link into the
downloader, it tries to extract `22382535409` as the story ID, which is
incorrect

That is what's on Discord

**Comment by AaronBenDaniel** [comment]
Ah yes, that's me. My Discord name is `sowansow`. #25 Should fix that issue.

**Comment by Julyski** [comment]
Oh, okay. I'll just try again later. Thank you very much.

**Comment by AaronBenDaniel** [comment]
In the meantime, before #25 is merged, you can just remove everything after the `?`.

For example, if you wanted to download

`https://www.wattpad.com/story/223825354?utm_source=android&utm_medium=facebook_messenger&utm_content=story_info&wp_page=story_details_button&wp_uname=MarieJimenez09`

you would (as of right now) get the error `This story does not exist, or has been deleted`, you can remove everything after the `?` to get

`https://www.wattpad.com/story/223825354`

this new link will work.

**Comment by Julyski** [comment]
Nope, still not working. I forgot to mention, I'm downloading on my mobile
phone, maybe there's an issue. I tried using three mobile phones and it has
the same issue,  it won't show the whole URL, just the story ID. I even
used your given link. But I'll just try it again later or tomorrow maybe
it'll be fixed.

**Comment by Julyski** [comment]
Thanks for helping.

**Comment by AaronBenDaniel** [comment]
> it won't show the whole URL, just the story ID

This is intentional, the download will still work even if it just shows the ID. After you've pasted the link, and only the ID appears in the input box, click the `Download` button.

**Comment by Julyski** [comment]
Thank you so much. It finally worked. I used the desktop version.
I appreciate all your help.
